# Generated by Django 5.1.1 on 2024-09-30 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categeory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author_name', models.CharField(max_length=200)),
                ('book_photo', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('author_photo', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('pages', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('rental_price_day', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('rent_period', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('statues', models.CharField(choices=[('Available', 'Available'), ('Rented', 'Rented'), ('Sold', 'Sold')], max_length=50)),
                ('categeory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms_app.categeory')),
            ],
        ),
    ]
